services:
  server:
    build: .
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 2000:2000

    env_file: ".env.prod"
    environment:
      - REDIS_HOST=redis

  redis:
    image: redis
    restart: unless-stopped

  db:
    image: postgres
    volumes:
      - /private/var/lib/postgresql/data:/var/lib/postgresql/data
    restart: unless-stopped
    ports:
      - 5432:5432

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
