name: Pre-commit Hooks

on: [push, pull_request]

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'  # Python version set to 3.12

      - name: Install pre-commit
        run: |
          pip install -r requirements.txt
          pre-commit install

      - name: Run pre-commit hooks
        run: pre-commit run --all-files
