name: Pre-commit Hooks

on: [push, pull_request]

jobs:
    pre-commit:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: "3.12" # Python version set to 3.12

            - name: Install pre-commit
              run: |
                  pip install pre-commit flake8 black isort
                  pre-commit install

            - name: Run flake8
              run: flake8 --verbose

            - name: Run pre-commit hooks
              run: pre-commit run --all-files --verbose

              - name: List files
                run: ls -R  # Список всех файлов в текущем каталоге
